### ISSUE TITLE
Unable to install any terraform versions

### ISSUE THREAD

**Issue by perobertson** [tfutils/tfenv#263]
As the title mentions, I am unable to install any Terraform versions due to the recent changes involving Hashicorp's key rotation.

- tfenv version: `2.2.1`
- keybase version: `keybase version 5.6.1-20210125164223+f3b21527b9`
- I am logged into keybase and following hashicorp

Attempting to install any version from **before** the Hashicorp key rotation leads to an error message like this:
```
tfenv install 0.14.10
Installing Terraform v0.14.10
Downloading release tarball from https://releases.hashicorp.com/terraform/0.14.10/terraform_0.14.10_linux_amd64.zip
################################################################################################################### 100.0%
Downloading SHA hash file from https://releases.hashicorp.com/terraform/0.14.10/terraform_0.14.10_SHA256SUMS
Downloading SHA hash signature file from https://releases.hashicorp.com/terraform/0.14.10/terraform_0.14.10_SHA256SUMS.sig
▶ ERROR openpgp: signature made by unknown entity
SHA256SUMS signature does not match!
```

Attempting to install any version from **after** the Hashicorp key rotation leads to an error message like this:
```
tfenv install 0.14.11
Installing Terraform v0.14.11
Downloading release tarball from https://releases.hashicorp.com/terraform/0.14.11/terraform_0.14.11_linux_amd64.zip
################################################################################################################### 100.0%
Downloading SHA hash file from https://releases.hashicorp.com/terraform/0.14.11/terraform_0.14.11_SHA256SUMS
Downloading SHA hash signature file from https://releases.hashicorp.com/terraform/0.14.11/terraform_0.14.11_SHA256SUMS.sig
▶ INFO Identifying hashicorp
✔ <new> public key fingerprint: C874 011F 0AB4 0511 0D02 1055 3436 5D94 72D7 468F
✖ <Deleted proof: 91a6e7f85d05c65630bef18951852d87348ffc4c> public key fingerprint: 91A6 E7F8 5D05 C656 30BE F189 5185 2D87 348F FC4C
You last followed hashicorp on 2021-01-08 17:22:25 EST
✔ <followed> admin of DNS zone hashicorp.com: found TXT entry keybase-site-verification=a-iv8bbkw3LgvmnT-p1jJ7Com9O-5GrOyFClq2-0iRQ [cached 2021-05-01 08:03:37 EDT]
▶ WARNING Some proofs were revoked:
✖ <Deleted proof: 91a6e7f85d05c65630bef18951852d87348ffc4c>
▶ ERROR failed to identify "hashicorp": Deleted proof: 91a6e7f85d05c65630bef18951852d87348ffc4c; 1 followed proof failed
SHA256SUMS signature does not match!
```

**Comment by anthraxx** [comment]
This should be fixed by https://github.com/tfutils/tfenv/pull/260

**Comment by blakemorgan** [comment]
For those still having issues, you'll need to "Accept" the changes Hasicorp made to their Keybase profile.

**Comment by perobertson** [comment]
> For those still having issues, you'll need to "Accept" the changes Hasicorp made to their Keybase profile.

That was the step I was missing. To do this I also needed to view the Hashicorp profile from the app. You may be able to do this from the web site if your gpg key is uploaded there.
I can also confirm that this was fixed in tfenv 2.2.2.

Thanks for all the work here in this project. It has been quite handy to have.
