### ISSUE TITLE
Can no longer download any older versions of terraform (0.14.6)

### ISSUE THREAD

**Issue by slmingol** [tfutils/tfenv#268]
### Version Info
```
$ tfenv
tfenv 2.2.1
Usage: tfenv <command> [<options>]

Commands:
   install       Install a specific version of Terraform
   use           Switch a version to use
   uninstall     Uninstall a specific version of Terraform
   list          List all installed versions
   list-remote   List all installable versions
   version-name  Print current version
   init          Update environment to use tfenv correctly.

```

### Example that fails
```
$ tfenv install
Installing Terraform v0.14.6
Downloading release tarball from https://releases.hashicorp.com/terraform/0.14.6/terraform_0.14.6_darwin_amd64.zip
############################################################################################################### 100.0%
Downloading SHA hash file from https://releases.hashicorp.com/terraform/0.14.6/terraform_0.14.6_SHA256SUMS
Downloading SHA hash signature file from https://releases.hashicorp.com/terraform/0.14.6/terraform_0.14.6_SHA256SUMS.sig
▶ ERROR openpgp: signature made by unknown entity
SHA256SUMS signature does not match!
```

I have a local file:

```
$ cat .terraform-version
0.14.6
```

Assuming the changes that were merged into 2.2.1 are the cause of this - https://github.com/tfutils/tfenv/pull/257.

**Comment by anthraxx** [comment]
fixed in 63bb5ff0350b0249d27e98c2334b2e13ca93e9d0

**Comment by slmingol** [comment]
@anthraxx ty confirmed that the `brew` version I had, 2.2.1 didn't have the fix, pulling down the latest had it.

```
$ tfenv
tfenv 2.2.1-2-gb4248c3
Usage: tfenv <command> [<options>]

Commands:
   install       Install a specific version of Terraform
   use           Switch a version to use
   uninstall     Uninstall a specific version of Terraform
   list          List all installed versions
   list-remote   List all installable versions
   version-name  Print current version
   init          Update environment to use tfenv correctly.

```

```
$ tfenv install
Installing Terraform v0.14.6
Downloading release tarball from https://releases.hashicorp.com/terraform/0.14.6/terraform_0.14.6_darwin_amd64.zip
############################################################################################################### 100.0%
Downloading SHA hash file from https://releases.hashicorp.com/terraform/0.14.6/terraform_0.14.6_SHA256SUMS
Downloading SHA hash signature file from https://releases.hashicorp.com/terraform/0.14.6/terraform_0.14.6_SHA256SUMS.72D7468F.sig
▶ INFO Identifying hashicorp
✔ <followed> public key fingerprint: C874 011F 0AB4 0511 0D02 1055 3436 5D94 72D7 468F
You last followed hashicorp on 2021-05-06 10:38:21 EDT
✔ <followed> admin of DNS zone hashicorp.com: found TXT entry keybase-site-verification=a-iv8bbkw3LgvmnT-p1jJ7Com9O-5GrOyFClq2-0iRQ [cached 2021-05-06 10:38:22 EDT]
Signature verified. Signed by hashicorp 2 weeks ago (2021-04-22 13:16:33 -0400 EDT).
PGP Fingerprint: c874011f0ab405110d02105534365d9472d7468f.
Archive:  tfenv_download.b7EkWj/terraform_0.14.6_darwin_amd64.zip
  inflating: /Users/smingolelli/.tfenv/versions/0.14.6/terraform
Installation of terraform v0.14.6 successful. To make this your default version, run 'tfenv use 0.14.6'
```

**Comment by tsira** [comment]
@slmingol did brew version 2.2.2 have the fix? I am still seeing this issue trying to install Terraform v0.11.15 with tfenv 2.2.2

**Comment by slmingol** [comment]
@tsira no I ended up just getting the tarball and installing it out-of-band from `brew`. I have this version which appears to be working atm:

```
$ tfenv
tfenv 2.2.1-2-gb4248c3
Usage: tfenv <command> [<options>]

Commands:
```

**Comment by kaleocheng** [comment]
got this issue as well. after some investigation. I found it's coz `hashicorp` changed their pgp key on keybase. so I fixed this by accepting their new pgp key on keybase.
